// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OcrApi.Data;

#nullable disable

namespace OcrApi.Migrations
{
    [DbContext(typeof(OcrDbContext))]
    [Migration("20260506011907_AddSampleDocumentProperties")]
    partial class AddSampleDocumentProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OcrApi.Models.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnalyzedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("bytea");

                    b.Property<string>("RawText")
                        .HasColumnType("text");

                    b.Property<string>("TableBlocksJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("analysis_results", (string)null);
                });

            modelBuilder.Entity("OcrApi.Models.DocumentPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisResultId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ImageBytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.ToTable("document_pages", (string)null);
                });

            modelBuilder.Entity("OcrApi.Models.DocumentSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisResultId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.ToTable("document_signatures", (string)null);
                });

            modelBuilder.Entity("OcrApi.Models.OcrProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRegex")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SearchHeuristic")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("ocr_properties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = false,
                            Name = "Signature",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = false,
                            Name = "FullName",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "date",
                            IsActive = true,
                            IsRegex = true,
                            Name = "DateOfBirth",
                            SearchHeuristic = "Date\\s*of\\s*Birth[\\s:]*(\\w+\\s+\\d{1,2},?\\s+\\d{4}|\\d{1,2}[\\/\\-]\\d{1,2}[\\/\\-]\\d{2,4})",
                            UpdatedAt = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            IsActive = true,
                            IsRegex = true,
                            Name = "BillingTotal",
                            SearchHeuristic = "\\$?\\s?\\d{1,3}(?:,\\d{3})*(?:\\.\\d{2})?",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            IsActive = true,
                            IsRegex = true,
                            Name = "ProcessingFee",
                            SearchHeuristic = "\\$?\\s?\\d{1,3}(?:,\\d{3})*(?:\\.\\d{2})?",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "InvoiceNumber",
                            SearchHeuristic = "Invoice\\s*(?:No\\.?|#|Number)[\\s:]*([A-Z0-9\\-]+)",
                            UpdatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "date",
                            IsActive = true,
                            IsRegex = true,
                            Name = "InvoiceDate",
                            SearchHeuristic = "Invoice\\s*Date[\\s:]*(\\d{1,2}[\\/\\-]\\d{1,2}[\\/\\-]\\d{2,4})",
                            UpdatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "date",
                            IsActive = true,
                            IsRegex = true,
                            Name = "DueDate",
                            SearchHeuristic = "Due\\s*Date[\\s:]*(\\d{1,2}[\\/\\-]\\d{1,2}[\\/\\-]\\d{2,4})",
                            UpdatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "AccountNumber",
                            SearchHeuristic = "Account\\s*(?:No\\.?|Number|#)[\\s:]*([*A-Z0-9\\-]+)",
                            UpdatedAt = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            IsActive = true,
                            IsRegex = true,
                            Name = "TaxAmount",
                            SearchHeuristic = "Tax[\\s:]*\\$?\\s*(\\d{1,3}(?:,\\d{3})*(?:\\.\\d{2})?)",
                            UpdatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "CaseNumber",
                            SearchHeuristic = "Case\\s*(?:No\\.?|Number|#)[\\s:]*([A-Z0-9\\-\\/]+)",
                            UpdatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "date",
                            IsActive = true,
                            IsRegex = true,
                            Name = "ContractDate",
                            SearchHeuristic = "(?:Contract|Agreement|Effective)\\s*Date[\\s:]*(\\d{1,2}[\\/\\-]\\d{1,2}[\\/\\-]\\d{2,4})",
                            UpdatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = false,
                            Name = "LegalParty",
                            SearchHeuristic = "Party",
                            UpdatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = false,
                            Name = "NotaryPublic",
                            SearchHeuristic = "Notary Public",
                            UpdatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "DocumentNumber",
                            SearchHeuristic = "Doc(?:ument)?\\.?\\s*(?:No\\.?|#|Number)[\\s:]*([A-Z0-9]+)",
                            UpdatedAt = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "PatientId",
                            SearchHeuristic = "(?:MRN|Patient\\s*ID|Patient\\s*Number)[\\s:]*([A-Z0-9\\-]+)",
                            UpdatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = false,
                            Name = "DiagnosisCode",
                            SearchHeuristic = "Diagnosis",
                            UpdatedAt = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "date",
                            IsActive = true,
                            IsRegex = true,
                            Name = "AdmissionDate",
                            SearchHeuristic = "(?:Admission\\s*Date|Date\\s*Admitt?ed)[\\s:]*(\\w+\\s+\\d{1,2},?\\s+\\d{4}|\\d{1,2}[\\/\\-]\\d{1,2}[\\/\\-]\\d{2,4})",
                            UpdatedAt = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "date",
                            IsActive = true,
                            IsRegex = true,
                            Name = "DischargeDate",
                            SearchHeuristic = "(?:Discharge[d]?\\s*Date|Date\\s*Discharge[d]?)[\\s:]*(\\w+\\s+\\d{1,2},?\\s+\\d{4}|\\d{1,2}[\\/\\-]\\d{1,2}[\\/\\-]\\d{2,4})",
                            UpdatedAt = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "PhysicianName",
                            SearchHeuristic = "(?:(?:Attending|Admitting)\\s*)?Physician[\\s:]*([^\\n]+)",
                            UpdatedAt = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "date",
                            IsActive = true,
                            IsRegex = true,
                            Name = "DocumentDate",
                            SearchHeuristic = "DATE[\\s:]+(\\d{1,2}[\\/\\-]\\d{1,2}[\\/\\-]\\d{2,4})",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "BillFromCompany",
                            SearchHeuristic = "Bill\\s*From:\\s+([^\\n\\r]+)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "BillToCompany",
                            SearchHeuristic = "Bill\\s*To:\\s+([^\\n\\r]+)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "BillToContact",
                            SearchHeuristic = "Attn:\\s*([^\\n\\r]+)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "ServiceDateRange",
                            SearchHeuristic = "(\\d{1,2}\\/\\d{1,2}\\/\\d{2,4}\\s*-\\s*\\d{1,2}\\/\\d{1,2}\\/\\d{2,4})",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            IsActive = true,
                            IsRegex = true,
                            Name = "HourlyRate",
                            SearchHeuristic = "Services\\s+\\$(\\d+(?:\\.\\d{2})?)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "number",
                            IsActive = true,
                            IsRegex = true,
                            Name = "TotalHours",
                            SearchHeuristic = "\\$\\d+(?:\\.\\d{2})?\\s+(\\d{3,})",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            IsActive = true,
                            IsRegex = true,
                            Name = "InvoiceTotal",
                            SearchHeuristic = "Total:\\s*\\$?([\\d,]+(?:\\.\\d{2})?)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "date",
                            IsActive = true,
                            IsRegex = true,
                            Name = "PaymentDate",
                            SearchHeuristic = "(\\d{1,2}\\/\\d{1,2}\\/\\d{4})\\s+Payment",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            IsActive = true,
                            IsRegex = true,
                            Name = "PaymentAmount",
                            SearchHeuristic = "Payment\\s+\\$?([\\d,]+(?:\\.\\d{2})?)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            IsActive = true,
                            IsRegex = true,
                            Name = "OutstandingBalance",
                            SearchHeuristic = "Balance\\s+\\$?([\\d,]+(?:\\.\\d{2})?)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "BankName",
                            SearchHeuristic = "Bank:\\s+([^\\n\\r]+)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "SwiftCode",
                            SearchHeuristic = "Swift\\s*(?:code|Code|CODE):\\s*([A-Z0-9]+)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "BankAccountName",
                            SearchHeuristic = "Account\\s*Name:\\s*([^\\n\\r]+)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "SignatoryName",
                            SearchHeuristic = "([^\\n]+)\\n(?:President|Director|CEO|CFO|COO|Manager|Officer|Secretary|Chairman|VP|Treasurer|Principal|Administrator|Partner)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "SignatoryTitle",
                            SearchHeuristic = "(President|Director|CEO|CFO|COO|Manager|Officer|Secretary|Chairman|Vice\\s+President|VP|Treasurer|Principal|Administrator)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            IsActive = true,
                            IsRegex = true,
                            Name = "SignatoryCompany",
                            SearchHeuristic = "(?:President|Director|CEO|CFO|COO|Manager|Officer|Secretary|Chairman|VP|Treasurer|Principal|Administrator)\\n([^\\n]+)",
                            UpdatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OcrApi.Models.SavedField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisResultId")
                        .HasColumnType("integer");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("ExtractedValue")
                        .HasColumnType("text");

                    b.Property<string>("ManualOverride")
                        .HasColumnType("text");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.ToTable("saved_fields", (string)null);
                });

            modelBuilder.Entity("OcrApi.Models.SavedTextBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisResultId")
                        .HasColumnType("integer");

                    b.Property<int>("BboxHeight")
                        .HasColumnType("integer");

                    b.Property<int>("BboxWidth")
                        .HasColumnType("integer");

                    b.Property<int>("BboxX")
                        .HasColumnType("integer");

                    b.Property<int>("BboxY")
                        .HasColumnType("integer");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<int>("Page")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.ToTable("saved_text_blocks", (string)null);
                });

            modelBuilder.Entity("OcrApi.Models.DocumentPage", b =>
                {
                    b.HasOne("OcrApi.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("Pages")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("OcrApi.Models.DocumentSignature", b =>
                {
                    b.HasOne("OcrApi.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("Signatures")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("OcrApi.Models.SavedField", b =>
                {
                    b.HasOne("OcrApi.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("Fields")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("OcrApi.Models.SavedTextBlock", b =>
                {
                    b.HasOne("OcrApi.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("TextBlocks")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("OcrApi.Models.AnalysisResult", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Pages");

                    b.Navigation("Signatures");

                    b.Navigation("TextBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
